local Games = {
    --id="游戏ID",name="游戏名字",type="游戏类型",friends="是否有好友房0x01好友房0x02休闲场0x04红包场",number ="金币房人数",playerCount="人数选择",isZuoXing4="是否有4人坐省",icon="大厅按钮图片",icon1="大厅按钮图片1",icons="大厅按钮图片2",icon8="八字玩法图片",ruleBtn="规则按钮图片",ruleCSB="规则网页节点",imgSynopsiss="游戏简介图片",imgSynopsis="游戏简介图片",luaCreateRoomFile="游戏创房lua文件",luaGameFile="游戏执行lua文件",imgDesk="游戏桌面图片", rules ="规则",describe = "桌面描述",
    [44]={ id=44, name="怀化红拐弯", type=1, friends=7, number =4, playerCount = "3,2,4", isZuoXing4=1, icon="game/paohuzi/44/icon.png", icons="game/paohuzi/44/icon1.png", icon1="game/paohuzi/44/icon2.png", icon8="game/paohuzi/44/icon8.png", icon_name="game/paohuzi/44/icon_name.png", ruleBtn="game/paohuzi/44/rule.png", ruleCSB="", imgSynopsiss="game/paohuzi/44/names.png", imgSynopsis="game/paohuzi/44/name.png", luaCreateRoomFile="RoomCreateLayer44", luaGameFile="game.paohuzi.44.GameLayer", imgDesk="game/paohuzi/44/watermark.png", rules ="规则简介：18胡起胡，15胡可自摸胡牌或有名堂胡牌，\n大小字胡4番起，名堂多样，玩法独特。"},
    [60]={ id=60, name="汉寿跑胡子", type=1, friends=7, number =3, playerCount = "3,2,4", isZuoXing4=1, icon="game/paohuzi/60/icon.png", icons="game/paohuzi/60/icon1.png", icon1="game/paohuzi/60/icon2.png", icon8="game/paohuzi/60/icon8.png", icon_name="game/paohuzi/60/icon_name.png", ruleBtn="game/paohuzi/60/rule.png", ruleCSB="", imgSynopsiss="game/paohuzi/60/names.png", imgSynopsis="game/paohuzi/60/name.png", luaCreateRoomFile="RoomCreateLayer60", luaGameFile="game.paohuzi.60.GameLayer", imgDesk="game/paohuzi/60/watermark.png", rules ="规则简介：15胡起胡，红胡、黑胡、对对胡、大字胡、小子胡、\n黄番、耍猴等多种名堂，不能接炮，只能胡牌墩上的牌。"}, 
    [78]={ id=78, name="红中麻将", type=3, friends=7, number =4, playerCount = "4,2,3", isZuoXing4=0, icon="game/majiang/78/icon.png", icons="game/majiang/78/icon1.png", icon1="game/majiang/78/icon2.png", icon8="game/majiang/78/icon8.png", icon_name="game/majiang/78/icon_name.png", ruleBtn="game/majiang/78/rule.png", ruleCSB="", imgSynopsiss="game/majiang/78/names.png", imgSynopsis="game/majiang/78/name.png", luaCreateRoomFile="RoomCreateLayer78", luaGameFile="game.majiang.78.GameLayer", imgDesk="game/majiang/78/watermark.png", rules ="规则简介：4张红中，红中可以代替任何牌，红中不能打出，\n起手4张红中可以直接胡牌。只能自摸，不准接炮。"}, 
    [79]={ id=79, name="转转麻将", type=3, friends=7, number =4, playerCount = "4,2,3", isZuoXing4=0, icon="game/majiang/79/icon.png", icons="game/majiang/79/icon1.png", icon1="game/majiang/79/icon2.png", icon8="game/majiang/79/icon8.png", icon_name="game/majiang/79/icon_name.png", ruleBtn="game/majiang/79/rule.png", ruleCSB="", imgSynopsiss="game/majiang/79/names.png", imgSynopsis="game/majiang/79/name.png", luaCreateRoomFile="RoomCreateLayer79", luaGameFile="game.majiang.79.GameLayer", imgDesk="game/majiang/79/watermark.png", rules ="规则简介：可自摸、可接炮，明杠3倍底分，暗杠每人2倍底分，公\n杠1倍底分。自摸2倍底分，中鸟加倍。不能跟胡。只算一五九为鸟。"},
    [80]={ id=80, name="长沙麻将", type=3, friends=1, number =4, playerCount = "4,2,3", isZuoXing4=0, icon="game/majiang/80/icon.png", icons="game/majiang/80/icon1.png", icon1="game/majiang/80/icon2.png", icon8="game/majiang/80/icon8.png", icon_name="game/majiang/80/icon_name.png", ruleBtn="game/majiang/80/rule.png", ruleCSB="", imgSynopsiss="game/majiang/80/names.png", imgSynopsis="game/majiang/80/name.png", luaCreateRoomFile="RoomCreateLayer80", luaGameFile="game.majiang.80.GameLayer", imgDesk="game/majiang/80/watermark.png", rules ="规则简介：可自摸、可接炮，明杠3倍底分，暗杠每人2倍底分，公\n杠1倍底分。自摸2倍底分，中鸟加倍。不能跟胡。只算一五九为鸟。"},
    [81]={ id=81, name="湘西猪笼子", type=3, friends=7, number =4, playerCount = "4,2,3", isZuoXing4=0, icon="game/majiang/81/icon.png", icons="game/majiang/81/icon1.png", icon1="game/majiang/81/icon2.png", icon8="game/majiang/81/icon8.png", icon_name="game/majiang/81/icon_name.png", ruleBtn="game/majiang/81/rule.png", ruleCSB="", imgSynopsiss="game/majiang/81/names.png", imgSynopsis="game/majiang/81/name.png", luaCreateRoomFile="RoomCreateLayer81", luaGameFile="game.majiang.81.GameLayer", imgDesk="game/majiang/81/watermark.png", rules ="规则简介：可自摸、可接炮，明杠3倍底分，暗杠每人2倍底分，公\n杠1倍底分。自摸2倍底分，中鸟加倍。不能跟胡。只算一五九为鸟。"},
    [82]={ id=82, name="怀化转转", type=3, friends=1, number =4, playerCount = "4,2,3", isZuoXing4=0, icon="game/majiang/82/icon.png", icons="game/majiang/82/icon1.png", icon1="game/majiang/82/icon2.png", icon8="game/majiang/82/icon8.png", icon_name="game/majiang/82/icon_name.png", ruleBtn="game/majiang/82/rule.png", ruleCSB="", imgSynopsiss="game/majiang/82/names.png", imgSynopsis="game/majiang/82/name.png", luaCreateRoomFile="RoomCreateLayer82", luaGameFile="game.majiang.82.GameLayer", imgDesk="game/majiang/82/watermark.png", rules ="规则简介：可自摸、可接炮，明杠3倍底分，暗杠每人2倍底分，公\n杠1倍底分。自摸2倍底分，中鸟加倍。不能跟胡。只算一五九为鸟。"},
    [83]={ id=83, name="湘西跑得快", type=2, friends=7, number =3, playerCount = "3,2", isZuoXing4=0, icon="game/puke/83/icon.png", icons="game/puke/83/icon1.png", icon1="game/puke/83/icon2.png", icon8="game/puke/83/icon8.png", icon_name="game/puke/83/icon_name.png", ruleBtn="game/puke/83/rule.png", ruleCSB="", imgSynopsiss="game/puke/83/names.png", imgSynopsis="game/puke/83/name.png", luaCreateRoomFile="RoomCreateLayer83", luaGameFile="game.puke.83.GameLayer", imgDesk="game/puke/83/watermark.png", rules ="规则简介：3人玩法，去掉大小王、方块2梅花2红桃2方块A，共48张\n牌，每人16张，首局红桃3先出。第二局开始由上游先出牌。"},
    [84]={ id=84, name="斗地主", type=2, friends=7, number =3, playerCount = "3", isZuoXing4=0, icon="game/puke/84/icon.png", icons="game/puke/84/icon1.png", icon1="game/puke/84/icon2.png", icon8="game/puke/84/icon8.png", icon_name="game/puke/84/icon_name.png", ruleBtn="game/puke/84/rule.png", ruleCSB="", imgSynopsiss="game/puke/84/names.png", imgSynopsis="game/puke/84/name.png", luaCreateRoomFile="RoomCreateLayer84", luaGameFile="game.puke.84.GameLayer", imgDesk="game/puke/84/watermark.png", rules ="规则简介：3人玩法，去掉大小王、方块2梅花2红桃2方块A，共48张\n牌，每人16张，首局红桃3先出。第二局开始由上游先出牌。"},
    [85]={ id=85, name="三打哈", type=2, friends=1, number =3, playerCount = "4,3", isZuoXing4=0, icon="game/puke/85/icon.png", icons="game/puke/85/icon1.png", icon1="game/puke/85/icon2.png", icon8="game/puke/85/icon8.png", icon_name="game/puke/85/icon_name.png", ruleBtn="game/puke/85/rule.png", ruleCSB="", imgSynopsiss="game/puke/85/names.png", imgSynopsis="game/puke/85/name.png", luaCreateRoomFile="RoomCreateLayer85", luaGameFile="game.puke.85.GameLayer", imgDesk="game/puke/85/watermark.png", rules ="规则简介：3人玩法，去掉大小王、方块2梅花2红桃2方块A，共48张\n牌，每人16张，首局红桃3先出。第二局开始由上游先出牌。"},
    [88]={ id=88, name="湘西二七十", type=1, friends=1, number =3, playerCount = "3,2,4", isZuoXing4=1, icon="game/paohuzi/88/icon.png", icons="game/paohuzi/88/icon1.png", icon1="game/paohuzi/88/icon2.png", icon8="game/paohuzi/88/icon8.png", icon_name="game/paohuzi/88/icon_name.png", ruleBtn="game/paohuzi/88/rule.png", ruleCSB="", imgSynopsiss="game/paohuzi/88/names.png", imgSynopsis="game/paohuzi/88/name.png", luaCreateRoomFile="RoomCreateLayer88", luaGameFile="game.paohuzi.88.GameLayer", imgDesk="game/paohuzi/88/watermark.png", rules ="规则简介：15胡起胡，红胡、黑胡、对对胡、大字胡、小子胡、\n黄番、耍猴等多种名堂，不能接炮，只能胡牌墩上的牌。"}, 
    [89]={ id=89, name="湘西跑胡子", type=1, friends=7, number =3, playerCount = "3,2,4", isZuoXing4=1, icon="game/paohuzi/89/icon.png", icons="game/paohuzi/89/icon1.png", icon1="game/paohuzi/89/icon2.png", icon8="game/paohuzi/89/icon8.png", icon_name="game/paohuzi/89/icon_name.png", ruleBtn="game/paohuzi/89/rule.png", ruleCSB="", imgSynopsiss="game/paohuzi/89/names.png", imgSynopsis="game/paohuzi/89/name.png", luaCreateRoomFile="RoomCreateLayer89", luaGameFile="game.paohuzi.89.GameLayer", imgDesk="game/paohuzi/89/watermark.png", rules ="规则简介：15胡起胡，红胡、黑胡、对对胡、大字胡、小子胡、\n黄番、耍猴等多种名堂，不能接炮，只能胡牌墩上的牌。"}, 
}

return Games
--1：好友房
--2：休闲场
--3：好友房和休闲场
--4：红包场
--5：好友房和红包场
--6：休闲场和红包场
--7：休闲场和好友房和红包场